#ifndef MINI_SHELL_CONFIG_H
#define MINI_SHELL_CONFIG_H

#define CONFIG_SHELL_PROMPT "\x1B[32m➜ \x1B[36m$ \x1B[0m"
#define CONFIG_SHELL_PRINTF_BUFFER_SIZE (128U)
#define CONFIG_SHELL_CMD_MAX_ARGC (10U)
#define CONFIG_SHELL_INPUT_BUFFSIZE (127U)
#define MINI_SHELL_BUILD_VERDION "1.0"
#endif